project_name: meanflownav
entity: zyt115200-harbin-institute-of-technology
run_name: meanflownav

# training setup
use_wandb: True #True
train: True
batch_size: 64
eval_batch_size: 64
epochs: 30
gpu_ids: [0]
num_workers: 8
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: meanflow
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]
obs_type: image
goal_type: image

# depth
depth:
  depth_encoder: vits
  dino_layer_idx:
    vits: [2, 5, 8, 11]
  pool_dim: 64
  out_dim:
    vits: 384
  weights_path: /media/zhanyt/Data/Zytisworking/flownav-main/weights/depth_anything_v2_vits.pth


# mask
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 3
alpha: 1e-4

# distance bounds
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: False

# MeanFlow specific parameters
meanflow:
  ratio: 0.75
  tr_sampler: "v1"
  P_mean_t: -0.6
  P_std_t: 1.6
  P_mean_r: -4.0
  P_std_r: 1.6
  norm_p: 0.75
  norm_eps: 0.001
  ema_decay: 0.9999
  ema_period: 1   #16

# dataset specific parameters
image_size: [96, 96]
datasets:
#    recon:
#     data_folder: /media/zhanyt/ZY/Datasets/flownav_data/nomad_dataset/recon
#     train: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/recon/train/ # path to train folder with traj_names.txt
#     test: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/recon/test/ # path to test folder with traj_names.txt
#     end_slack: 3 # because many trajectories end in collisions
#     goals_per_obs: 1 # how many goals are sampled per observation
#     negative_mining: True # negative mining from the ViNG paper (Shah et al.)
#     waypoint_spacing: 1
   custom:
    data_folder: /media/zhanyt/ZY/Datasets/flownav_data/nomad_dataset/custom_4_29_lab
    train: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/custom_4_29_lab/train/ # path to train folder with traj_names.txt
    test: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/custom_4_29_lab/test/ # path to test folder with traj_names.txt
    end_slack: 3
    goals_per_obs: 2 # increase dataset size
    negative_mining: True
    waypoint_spacing: 1
  # custom:
  #   data_folder: /media/zhanyt/ZY/Datasets/flownav_data/nomad_dataset/custom_4_29_hallway
  #   train: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/custom_4_29_hallway/train/ # path to train folder with traj_names.txt
  #   test: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/custom_4_29_hallway/test/ # path to test folder with traj_names.txt
  #   end_slack: 3
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: True
  #   waypoint_spacing: 1
  # tartan:
  #   data_folder: /media/zhanyt/ZY/Datasets/flownav_data/nomad_dataset/tartan
  #   train: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/tartan/train/ # path to train folder with traj_names.txt
  #   test: /media/zhanyt/ZY/Datasets/flownav_data/data_splits/tartan/test/ # path to test folder with traj_names.txt
  #   end_slack: 3
  #   goals_per_obs: 1 # increase dataset size
  #   negative_mining: True
  #   waypoint_spacing: 1

# logging
print_log_freq: 50
image_log_freq: 1
num_images_log: 8
pairwise_test_freq: 0
eval_fraction: 0.25
wandb_log_freq: 10
eval_freq: 1

#load_run: /media/zhanyt/ZY/Datasets/flownav-main/logs/meanflownav/meanflownav_2026_04_11_18_06_16/latest.pth
#load_run: /media/zhanyt/ZY/Datasets/flownav-main/logs/meanflownav/meanflownav_2026_04_11_23_14_32/latest.pth

#load_run: /media/zhanyt/ZY/Datasets/flownav-main/logs/meanflownav/meanflownav_2026_04_13_14_41_11/latest.pth
#load_run: /media/zhanyt/ZY/Datasets/flownav-main/logs/meanflownav/meanflownav_2026_04_13_15_02_47/latest.pth


#load_run: /media/zhanyt/ZY/Datasets/flownav-main/logs/meanflownav/meanflownav_2026_04_15_13_50_04/latest.pth  #含两个数据集
# load_run: /media/zhanyt/Data/Zytisworking/flownav-main/logs/meanflownav/meanflownav_2026_04_15_20_23_25/latest.pth   #在上面的基础上又在custom上训练了一轮
# load_run: /media/zhanyt/Data/Zytisworking/flownav-main/logs/meanflownav/meanflownav_2026_04_30_00_32_36/latest.pth #在上面的基础上又在custom_4_29上训练了一轮
# load_run: /media/zhanyt/Data/Zytisworking/flownav-main/logs/meanflownav/meanflownav_2026_05_07_23_47_24/latest.pth #在上面的基础上又在custom_4_29_lab上训练了一轮
# load_run: /media/zhanyt/Data/Zytisworking/flownav-main/logs/meanflownav/meanflownav_2026_05_09_20_40_22/latest.pth #从头开始在custom_4_29+recon上训练了2epochs

load_run: /media/zhanyt/Data/Zytisworking/flownav-main/logs/meanflownav/meanflownav_2026_05_10_17_28_56/latest.pth #在0509的基础上在lab上训练了一整轮
