project_name: meanflownav
entity: scrach
run_name: meanflownav

# training setup
use_wandb: True
train: True
batch_size: 2
eval_batch_size: 2
epochs: 30
gpu_ids: [0]
num_workers: 8
lr: 0.0001
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: meanflow
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]
obs_type: image
goal_type: image

# depth
depth:
  depth_encoder: vits
  dino_layer_idx:
    vits: [2, 5, 8, 11]
  pool_dim: 64
  out_dim:
    vits: 384
  weights_path: /data/home/libo/project/flownav/model_weights/depth_anything_v2_vits.pth

# mask
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 3
alpha: 0.0001

# distance bounds
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: False

# MeanFlow specific parameters
meanflow:
  ratio: 0.75
  tr_sampler: "v1"
  P_mean_t: -0.6
  P_std_t: 1.6
  P_mean_r: -4.0
  P_std_r: 1.6
  norm_p: 0.75
  norm_eps: 0.001
  ema_decay: 0.9999
  ema_period: 16

# dataset specific parameters
image_size: [96, 96]
datasets:
  go_stanford:
    data_folder: /data/home/mobilemani/downloads/data/go_stanford/go_stanford
    train: /data/home/libo/project/flownav/data_splits/go_stanford/train/
    test: /data/home/libo/project/flownav/data_splits/go_stanford/test/
    end_slack: 0
    goals_per_obs: 2
    negative_mining: True
    waypoint_spacing: 1

# logging
print_log_freq: 500
image_log_freq: 1000
num_images_log: 8
pairwise_test_freq: 0
eval_fraction: 0.25
wandb_log_freq: 10
eval_freq: 1
